"use client";

import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
} from "recharts";
import { FiDownload, FiFileText } from "react-icons/fi";

export default function ReportsSection() {
  // Dummy data
  const salesData = [
    { month: "Jan", revenue: 32000 },
    { month: "Feb", revenue: 28000 },
    { month: "Mar", revenue: 36000 },
    { month: "Apr", revenue: 41000 },
    { month: "May", revenue: 39000 },
    { month: "Jun", revenue: 45000 },
  ];

  const servicesData = [
    { name: "Cleaning", value: 120 },
    { name: "Extraction", value: 80 },
    { name: "Braces", value: 40 },
    { name: "Root Canal", value: 25 },
  ];

  const COLORS = ["#2563eb", "#16a34a", "#f59e0b", "#dc2626"];

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <h1 className="text-2xl font-bold">📊 Reports</h1>
        <button className="btn btn-primary flex items-center gap-2">
          <FiDownload /> Export Report
        </button>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="stat bg-base-200 rounded-xl p-4 shadow">
          <div className="stat-title">Total Revenue</div>
          <div className="stat-value text-primary">₱215k</div>
          <div className="stat-desc">+12% from last month</div>
        </div>
        <div className="stat bg-base-200 rounded-xl p-4 shadow">
          <div className="stat-title">Total Patients Served</div>
          <div className="stat-value text-secondary">265</div>
          <div className="stat-desc">+18 new this month</div>
        </div>
        <div className="stat bg-base-200 rounded-xl p-4 shadow">
          <div className="stat-title">Top Service</div>
          <div className="stat-value text-accent">Cleaning</div>
          <div className="stat-desc">120 sessions</div>
        </div>
      </div>

      {/* Charts */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Revenue Chart */}
        <div className="card bg-base-100 shadow p-4">
          <h2 className="font-bold mb-4">Monthly Revenue</h2>
          <ResponsiveContainer width="100%" height={250}>
            <BarChart data={salesData}>
              <XAxis dataKey="month" />
              <YAxis />
              <Tooltip />
              <Bar dataKey="revenue" fill="#2563eb" radius={[6, 6, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>

        {/* Services Chart */}
        <div className="card bg-base-100 shadow p-4">
          <h2 className="font-bold mb-4">Services Breakdown</h2>
          <ResponsiveContainer width="100%" height={250}>
            <PieChart>
              <Pie
                data={servicesData}
                cx="50%"
                cy="50%"
                outerRadius={90}
                fill="#8884d8"
                dataKey="value"
                label
              >
                {servicesData.map((entry, index) => (
                  <Cell
                    key={`cell-${index}`}
                    fill={COLORS[index % COLORS.length]}
                  />
                ))}
              </Pie>
              <Tooltip />
            </PieChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Recent Reports Table */}
      <div className="card bg-base-100 shadow">
        <div className="card-body p-0">
          <div className="overflow-x-auto">
            <table className="table table-zebra">
              <thead>
                <tr>
                  <th>Report</th>
                  <th>Date</th>
                  <th>Generated By</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Monthly Revenue Report</td>
                  <td>Oct 1, 2025</td>
                  <td>Admin</td>
                  <td>
                    <button className="btn btn-xs btn-outline flex gap-1">
                      <FiFileText /> View
                    </button>
                  </td>
                </tr>
                <tr>
                  <td>Services Usage Report</td>
                  <td>Sep 25, 2025</td>
                  <td>Admin</td>
                  <td>
                    <button className="btn btn-xs btn-outline flex gap-1">
                      <FiFileText /> View
                    </button>
                  </td>
                </tr>
                <tr>
                  <td>Patients Report</td>
                  <td>Sep 15, 2025</td>
                  <td>Staff</td>
                  <td>
                    <button className="btn btn-xs btn-outline flex gap-1">
                      <FiFileText /> View
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}
